auth:
  registry.hub.docker.com:
    username: USERNAME
    password: PASSWORD
images:
  k8s.gcr.io/prometheus-adapter/prometheus-adapter: selina5288/prometheus-adapter
  k8s.gcr.io/kube-state-metrics/kube-state-metrics:v2.2.3: selina5288/kube-state-metrics:v2.2.3
  
  
  
